services:
  db:
    image: postgres:16
    container_name: team3-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      POSTGRES_DB: ${POSTGRES_DB:-odoo_db}
    volumes:
      - team3_db_data:/var/lib/postgresql/data
    networks:
      - eventmind3-network

  odoo:
    image: odoo:18
    container_name: team3-odoo
    restart: always
    depends_on:
      - db
    command: -d odoo_db
    environment:
      HOST: db
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      PROXY_MODE: 1
    volumes:
      - team3_odoo_data:/var/lib/odoo
    networks:
      - eventmind3-network

  nginx:
    image: nginx:latest
    container_name: team3-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/odoo.conf
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    depends_on:
      - odoo  
    networks:
      - eventmind3-network
  
  agent:
    build: ./agent
    container_name: team3-agent
    restart: always
    environment:
      - ODOO_HOST=http://team3-odoo:8069
      - ${DB_NAME:-odoo_db}
      - ${ODOO_USER:-odoo@ya.ru}
      - ${ODOO_PASS:-odoo}
    depends_on:
      - odoo
    networks:
      - eventmind3-network

networks:
  eventmind3-network:
    driver: bridge

volumes:
  team3_db_data:
  team3_odoo_data: