services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:16
    container_name: team3-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - team3_db_data:/var/lib/postgresql/data
    networks:
      - eventmind3-network

  # 2. ERP система Odoo
  odoo:
    image: odoo:18
    container_name: team3-odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - team3_odoo_data:/var/lib/odoo
    networks:
      - eventmind3-network

  # 3. (FastAPI)
  api:
    image: koyq/event-mind:latest
    container_name: eventmind3-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-odoo}:${POSTGRES_PASSWORD:-odoo}@db:5432/${POSTGRES_DB:-postgres}
    networks:
      - eventmind3-network

  # 4. AI-Агент
  ai_agent:
    image: koyq/event-mind:latest
    container_name: eventmind3-ai
    depends_on:
      - api
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-odoo}:${POSTGRES_PASSWORD:-odoo}@db:5432/${POSTGRES_DB:-postgres}
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
    networks:
      - eventmind3-network

networks:
  eventmind3-network:
    driver: bridge

volumes:
  team3_db_data:
  team3_odoo_data: